### ISSUE TITLE
errors when running text demo

### ISSUE THREAD

**Issue by elhamAm** [etienne87/pytorch-stream-dataloader#5]
Hello,

I am running the text demo and I get the errors below, can you please help?
   component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/elham/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/elham/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "examples/demo_text.py", line 13, in read_dataset
    dataloader = TextLoader(example_text, batch_size, num_workers, 24)
  File "/home/elham/Desktop/pytorch-stream-dataloader/examples/text_stream_dataset.py", line 37, in __init__
    super().__init__(texts, iterator_fun, batch_size, num_workers, collate_fn, "data")
TypeError: __init__() takes 4 positional arguments but 7 were given

**Comment by elhamAm** [comment]
Also, how do you run the video demo? For me it just shows a list of commands.

**Comment by etienne87** [comment]
thank you for trying out the demo. did you install fire? i will push some modifs + instructions on how to run. for the video you can look at the code: def read_dataset(path, batch_size=4, num_workers=2, num_batches=400, viz=True): so the path is just a folder with videos (.mp4) inside. I will try it myself and check if that still works though and let you know, as i did MRs recently and did not rechecked this part.

**Comment by elhamAm** [comment]
Thanks for the quick reply. Yes I installed fire

**Comment by elhamAm** [comment]
thank you very much for the coming instructions!

**Comment by elhamAm** [comment]
And just to make sure, in your version of a dataset, do you assume that only the first single frame of let's say 5 videos are available and then the second frame of the 5 videos? In my case the videos are being streamed and I need to process them real-time

**Comment by etienne87** [comment]
yes the idea of this package is that we are streaming data, for continuous learning or rnn/ temporally coherent processing

**Comment by etienne87** [comment]
ok i fixed demo_text and demo_video. the only annoying thing is that currently you need a lot of dependencies to make it run (i will remove to make it simpler to run)
you can run demos after running "pip install ." in the folder:
- python examples/demo_text.py
- python examples/demo_video.py [folder_with_videos]
If you put nothing instead of [folder_with_videos] it will start mock streams of random data of size (3,240,320)

For demo_video you might need a lot of dependencies:
- opencv
- torchvision
- decord
- scikit-video
It is not really critical for the sake of the demo to install all this, you can discard some code to make it run without decord or without scikit for instance.
Let me know if everything runs for you.

**Comment by elhamAm** [comment]
Alright thanks a bunch ! I will try it out and let you know.

**Comment by etienne87** [comment]
Closing
